iaato_iaato_homepage:
    pattern:  /home
    defaults: { _controller: IaatoIaatoBundle:Home:index }

iaato_capitaine:
    pattern: /capitaine
    defaults: { _controller: IaatoMapBundle:Default:index }

iaato_secretariat:
    pattern: /secretariat
    defaults: { _controller: IaatoIaatoBundle:Secretariat:index }

iaato_ship:
    pattern: /secretariat/ship
    defaults: { _controller: IaatoIaatoBundle:Ship:index }

iaato_ship_add:
    pattern: /secretariat/ship/add
    defaults: { _controller: IaatoIaatoBundle:Ship:add }

iaato_ship_remove:
    pattern: /secretariat/ship/delete
    defaults: { _controller: IaatoIaatoBundle:Ship:remove }

iaato_connexion:
    pattern: /connexion
    defaults: { _controller: IaatoIaatoBundle:Connexion:index }

iaato_contact:
    pattern: /contact
    defaults: { _controller:IaatoIaatoBundle:Contact:index }

patch:
    pattern: /
    defaults: { _controller:IaatoIaatoBundle:Home:index }

iaato_admin:
    pattern: /admin
    defaults: { _controller:IaatoIaatoBundle:Admin:index }
    
iaato_society:
    pattern: /secretariat/society
    defaults: { _controller:IaatoIaatoBundle:Society:index }

iaato_society_add:
    pattern: /secretariat/society/add
    defaults: { _controller:IaatoIaatoBundle:Society:add }
    
iaato_society_remove:
    pattern: /secretariat/society/remove
    defaults: { _controller:IaatoIaatoBundle:Society:remove }
    
iaato_site:
    pattern: /secretariat/site
    defaults: { _controller:IaatoIaatoBundle:Site:index }

iaato_site_add:
    pattern: /secretariat/site/add
    defaults: { _controller:IaatoIaatoBundle:Site:add }

iaato_site_remove:
    pattern: /secretariat/site/remove
    defaults: { _controller:IaatoIaatoBundle:Site:remove }

iaato_activity:
    pattern: /secretariat/activity
    defaults: { _controller:IaatoIaatoBundle:Activity:index }
    

iaato_activity_add:
    pattern: /secretariat/activity/add
    defaults: { _controller:IaatoIaatoBundle:Activity:add }


iaato_activity_remove:
    pattern: /secretariat/activity/remove
    defaults: { _controller:IaatoIaatoBundle:Activity:remove }


iaato_type:
    pattern: /secretariat/type
    defaults: { _controller:IaatoIaatoBundle:Type:index }
    
iaato_type_add:
    pattern: /secretariat/type/add
    defaults: { _controller:IaatoIaatoBundle:Type:add }
    
iaato_type_remove:
    pattern: /secretariat/type/remove
    defaults: { _controller:IaatoIaatoBundle:Type:remove }

iaato_csv_download:
    pattern: /secretariat/csv/download
    defaults: { _controller:IaatoIaatoBundle:CSVDown:index }
    
iaato_csv_upload:
    pattern: /secretariat/csv/upload
    defaults: { _controller:IaatoIaatoBundle:CSVUp:index }