<?php

namespace Iaato\IaatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubZoneRepository extends EntityRepository
{
}
