parameters:
#    iaato_user.example.class: Iaato\UserBundle\Example

services:
#    iaato_user.example:
#        class: %iaato_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
